name: Update Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update to (e.g., 0.1.0)'
        required: true
        default: ''

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update version in Cargo.toml
        run: |
          # Remove the 'v' prefix if it exists
          VERSION="${{ github.event.inputs.version }}"
          VERSION="${VERSION#v}"
          
          # Update version in Cargo.toml
          sed -i "s/^version = \".*\"/version = \"$VERSION\"/" Cargo.toml
          
          # Commit and push changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Cargo.toml
          git commit -m "Bump version to $VERSION"
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push
          git push --tags 